In [1]:
import pandas as pd

In [2]:
data={
    'employee':['amit','arya','minnu','ammu','anu','aathi'],
    'department':['IT','HR','IT','FINANCE','HR','IT'],
    'city':['calicut','chennai','delhi','mumbai','chennai','calicut'],
    'salary':[70000,30000,100000,40000,80000,90000],
    'experience':[1,4,5,8,9,4]

}
df=pd.DataFrame(data)
df

  employee department     city  salary  experience
0     amit         IT  calicut   70000           1
1     arya         HR  chennai   30000           4
2    minnu         IT    delhi  100000           5
3     ammu    FINANCE   mumbai   40000           8
4      anu         HR  chennai   80000           9
5    aathi         IT  calicut   90000           4

In [3]:
df.groupby('department')

In [4]:
df.groupby('department')['salary'].mean()

department
FINANCE    40000.000000
HR         55000.000000
IT         86666.666667
Name: salary, dtype: float64

In [6]:
df.groupby('department')['salary'].sum()

department
FINANCE     40000
HR         110000
IT         260000
Name: salary, dtype: int64

In [7]:
df.groupby('department')['experience'].max()

department
FINANCE    8
HR         9
IT         5
Name: experience, dtype: int64

In [10]:
df.groupby('department')['salary'].agg(['mean','sum','min','max'])

                    mean     sum    min     max
department
FINANCE     40000.000000   40000  40000   40000
HR          55000.000000  110000  30000   80000
IT          86666.666667  260000  70000  100000

In [11]:
df.groupby('department').agg({
    'salary':['mean','sum'],
    'experience':['mean','max']
})

                  salary         experience
                    mean     sum       mean max
department
FINANCE     40000.000000   40000   8.000000   8
HR          55000.000000  110000   6.500000   9
IT          86666.666667  260000   3.333333   5

In [12]:
df.groupby('department').agg(
    avg_salary=('salary','mean'),
    total_salary=('salary','sum'),
    max_experience=('experience','max')
)

              avg_salary  total_salary  max_experience
department
FINANCE     40000.000000         40000               8
HR          55000.000000        110000               9
IT          86666.666667        260000               5

In [28]:
employees=pd.DataFrame({
    'empID':[1,2,3,4],
    'name':['ammu','anu','arya','diya'],
    'deptID':[101,102,101,103],
    'salary':[10000,30000,50000,50000]
})

departments =pd.DataFrame({
    'deptID':[101,102,104],
    'department':['IT','HR','IT']
})

employees,departments

(   empID  name  deptID  salary
 0      1  ammu     101   10000
 1      2   anu     102   30000
 2      3  arya     101   50000
 3      4  diya     103   50000,
    deptID department
 0     101         IT
 1     102         HR
 2     104         IT)

In [19]:
pd.merge(employees,departments,on="deptID",how="inner")

   empID  name  deptID  salary department
0      1  ammu     101   10000         IT
1      2   anu     102   30000         HR
2      3  arya     101   50000         IT

In [21]:
pd.merge(employees,departments,on="deptID",how='left')

   empID  name  deptID  salary department
0      1  ammu     101   10000         IT
1      2   anu     102   30000         HR
2      3  arya     101   50000         IT
3      4  diya     103   50000        NaN

In [22]:
pd.merge(employees,departments,on="deptID",how='right')

   empID  name  deptID   salary department
0    1.0  ammu     101  10000.0         IT
1    3.0  arya     101  50000.0         IT
2    2.0   anu     102  30000.0         HR
3    NaN   NaN     104      NaN         IT

In [23]:
pd.merge(employees,departments,on="deptID",how='outer')

   empID  name  deptID   salary department
0    1.0  ammu     101  10000.0         IT
1    3.0  arya     101  50000.0         IT
2    2.0   anu     102  30000.0         HR
3    4.0  diya     103  50000.0        NaN
4    NaN   NaN     104      NaN         IT

In [24]:
pd.merge(employees,departments,on='deptID')

   empID  name  deptID  salary department
0      1  ammu     101   10000         IT
1      2   anu     102   30000         HR
2      3  arya     101   50000         IT

In [29]:
employees.set_index('deptID',inplace=True)
departments.set_index('deptID',inplace=True)
employees.join(departments)

        empID  name  salary department
deptID
101         1  ammu   10000         IT
102         2   anu   30000         HR
101         3  arya   50000         IT
103         4  diya   50000        NaN

In [30]:
df1=employees.iloc[:2]
df2=employees.iloc[2:]
pd.concat([df1,df2])

        empID  name  salary
deptID
101         1  ammu   10000
102         2   anu   30000
101         3  arya   50000
103         4  diya   50000

In [31]:
extra=pd.DataFrame({'bonus':[2000,23000,8000,5000]})
pd.concat([employees.reset_index(drop=True),extra],axis=1)

   empID  name  salary  bonus
0      1  ammu   10000   2000
1      2   anu   30000  23000
2      3  arya   50000   8000
3      4  diya   50000   5000

In [33]:
pd.concat([df1,df2])

        empID  name  salary
deptID
101         1  ammu   10000
102         2   anu   30000
101         3  arya   50000
103         4  diya   50000