In [1]:
import pandas as pd

In [2]:
import numpy as np

In [84]:

data={
    'ID':[1,2,3,4,2,5],
    'NAME':['ali','john','sara','None','john','david'],
    'AGE':[24,np.nan,22,20,np.nan,34],
    'SALARY':[50000,40000,None,70000,30000,20000],
    'DEPARTMENT':['HR','IT','FINANCE',None,'IT','IT']

}

df=pd.DataFrame(data)
df

   ID   NAME   AGE   SALARY DEPARTMENT
0   1    ali  24.0  50000.0         HR
1   2   john   NaN  40000.0         IT
2   3   sara  22.0      NaN    FINANCE
3   4   None  20.0  70000.0        NaN
4   2   john   NaN  30000.0         IT
5   5  david  34.0  20000.0         IT

In [7]:
df.isna()

      ID   NAME    AGE  SALARY  DEPARTMENT
0  False  False  False   False       False
1  False  False   True   False       False
2  False  False  False    True       False
3  False  False  False   False        True
4  False  False   True   False       False
5  False  False  False   False       False

In [8]:
df.isna().sum()

ID            0
NAME          0
AGE           2
SALARY        1
DEPARTMENT    1
dtype: int64

In [55]:
df.dropna()

  NAME    AGE  MONTHLY INCOME     CITY JOINING DATE
0    1    ali            24.0  50000.0           HR
2    3   sara            22.0  42000.0      FINANCE
5    5  david            34.0  20000.0           IT

In [10]:
df.dropna(axis=1)

   ID   NAME
0   1    ali
1   2   john
2   3   sara
3   4   None
4   2   john
5   5  david

In [12]:
df['AGE'].fillna(0,inplace=True)

C:\Users\mvaru\AppData\Local\Temp\ipykernel_16640\256681973.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['AGE'].fillna(0,inplace=True)

0    24.0
1     0.0
2    22.0
3    20.0
4     0.0
5    34.0
Name: AGE, dtype: float64

In [13]:
df['AGE'].fillna(df['AGE'].mean(),inplace=True)

C:\Users\mvaru\AppData\Local\Temp\ipykernel_16640\1654625185.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['AGE'].fillna(df['AGE'].mean(),inplace=True)

0    24.0
1    25.0
2    22.0
3    20.0
4    25.0
5    34.0
Name: AGE, dtype: float64

In [14]:
df['NAME'].fillna("unknown",inplace=True)

C:\Users\mvaru\AppData\Local\Temp\ipykernel_16640\1261676271.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['NAME'].fillna("unknown",inplace=True)

0      ali
1     john
2     sara
3     None
4     john
5    david
Name: NAME, dtype: str

In [22]:
df['SALARY']=df['SALARY']=df['SALARY'].astype(float)

In [23]:
df['SALARY']

0    50000.0
1    40000.0
2        NaN
3    70000.0
4    30000.0
5    20000.0
Name: SALARY, dtype: float64

In [29]:
df['SALARY']=df['SALARY'].fillna(df['SALARY'].mean())

In [30]:
df['SALARY']

0    50000.0
1    40000.0
2    42000.0
3    70000.0
4    30000.0
5    20000.0
Name: SALARY, dtype: float64

In [31]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool

In [32]:
df.drop_duplicates()

   ID   NAME   AGE   SALARY DEPARTMENT
0   1    ali  24.0  50000.0         HR
1   2   john   NaN  40000.0         IT
2   3   sara  22.0  42000.0    FINANCE
3   4   None  20.0  70000.0        NaN
4   2   john   NaN  30000.0         IT
5   5  david  34.0  20000.0         IT

In [34]:
df.rename(columns={"SALARY":"MONTHLY_SALARY"},inplace=True)

In [47]:
df

   NAME    AGE  MONTHLY INCOME     CITY JOINING DATE
0     1    ali            24.0  50000.0           HR
1     2   john             NaN  40000.0           IT
2     3   sara            22.0  42000.0      FINANCE
3     4   None            20.0  70000.0          NaN
4     2   john             NaN  30000.0           IT
5     5  david            34.0  20000.0           IT

In [50]:
df["NAME"]=df['NAME'].astype(str).str.lower()

In [62]:
df['NAME']=df["NAME"].str.upper()

In [63]:
df['NAME']

0      ALI
1     JOHN
2     SARA
3     NONE
4     JOHN
5    DAVID
Name: NAME, dtype: str

In [64]:
df

   ID   NAME   AGE   SALARY DEPARTMENT
0   1    ALI  24.0  50000.0         HR
1   2   JOHN   NaN  40000.0         IT
2   3   SARA  22.0      NaN    FINANCE
3   4   NONE  20.0  70000.0        NaN
4   2   JOHN   NaN  30000.0         IT
5   5  DAVID  34.0  20000.0         IT

In [65]:
df[df['NAME'].str.contains("A",case=True)]

   ID   NAME   AGE   SALARY DEPARTMENT
0   1    ALI  24.0  50000.0         HR
2   3   SARA  22.0      NaN    FINANCE
5   5  DAVID  34.0  20000.0         IT

In [66]:
df

   ID   NAME   AGE   SALARY DEPARTMENT
0   1    ALI  24.0  50000.0         HR
1   2   JOHN   NaN  40000.0         IT
2   3   SARA  22.0      NaN    FINANCE
3   4   NONE  20.0  70000.0        NaN
4   2   JOHN   NaN  30000.0         IT
5   5  DAVID  34.0  20000.0         IT

In [67]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          6 non-null      int64
 1   NAME        6 non-null      str
 2   AGE         4 non-null      float64
 3   SALARY      5 non-null      float64
 4   DEPARTMENT  5 non-null      str
dtypes: float64(2), int64(1), str(2)
memory usage: 372.0 bytes

In [83]:
df.describe

RecursionError: maximum recursion depth exceeded

In [ ]:
df['JOINING DATE']=pd.to_datetime(['20/2/2001','23/4/2001','26/5/2006','4/5/2010','10/4/2003','4/8/2003'])

C:\Users\mvaru\AppData\Local\Temp\ipykernel_16640\1697813898.py:1: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['JOINING DATE']=pd.to_datetime(['20/2/2001','23/4/2001','4/5/2010','10/4/2003','26/5/2006','4/8/2003'])

In [72]:
df['JOINING DATE']

0   2001-02-20
1   2001-04-23
2   2010-05-04
3   2003-04-10
4   2006-05-26
5   2003-08-04
Name: JOINING DATE, dtype: datetime64[us]

In [85]:
df

   ID   NAME   AGE   SALARY DEPARTMENT
0   1    ali  24.0  50000.0         HR
1   2   john   NaN  40000.0         IT
2   3   sara  22.0      NaN    FINANCE
3   4   None  20.0  70000.0        NaN
4   2   john   NaN  30000.0         IT
5   5  david  34.0  20000.0         IT

In [94]:
df["AGE"]=df['AGE'].ffill()

In [95]:
df['AGE']

0    24.0
1    24.0
2    22.0
3    20.0
4    20.0
5    34.0
Name: AGE, dtype: float64

In [99]:
df['SALARY']=df['SALARY'].ffill()

In [100]:
df['SALARY']

0    50000.0
1    40000.0
2    40000.0
3    70000.0
4    30000.0
5    20000.0
Name: SALARY, dtype: float64

In [101]:
df['DEPARTMENT']=df['DEPARTMENT'].bfill()

In [103]:
df['DEPARTMENT']

0         HR
1         IT
2    FINANCE
3         IT
4         IT
5         IT
Name: DEPARTMENT, dtype: str

In [104]:
df

   ID   NAME   AGE   SALARY DEPARTMENT  AGE_ffill
0   1    ali  24.0  50000.0         HR       24.0
1   2   john  24.0  40000.0         IT       24.0
2   3   sara  22.0  40000.0    FINANCE       22.0
3   4   None  20.0  70000.0         IT       20.0
4   2   john  20.0  30000.0         IT       20.0
5   5  david  34.0  20000.0         IT       34.0

In [105]:
df['NAME']=df['NAME'].bfill()

In [106]:
df['NAME']

0      ali
1     john
2     sara
3     None
4     john
5    david
Name: NAME, dtype: str

In [108]:
df[df['AGE']>30]

   ID   NAME   AGE   SALARY DEPARTMENT  AGE_ffill
5   5  david  34.0  20000.0         IT       34.0

In [109]:
df[df["DEPARTMENT"]=='IT']

   ID   NAME   AGE   SALARY DEPARTMENT  AGE_ffill
1   2   john  24.0  40000.0         IT       24.0
3   4   None  20.0  70000.0         IT       20.0
4   2   john  20.0  30000.0         IT       20.0
5   5  david  34.0  20000.0         IT       34.0

In [117]:
data={
    "date":pd.date_range("2024/01/01",periods=6),
    "sales":[100,np.nan,np.nan,160,np.nan,200],
    "city":['bangalore','None','bangalore',None,'mumbai',None]

}
df=pd.DataFrame(data)
df

        date  sales       city
0 2024-01-01  100.0  bangalore
1 2024-01-02    NaN       None
2 2024-01-03    NaN  bangalore
3 2024-01-04  160.0        NaN
4 2024-01-05    NaN     mumbai
5 2024-01-06  200.0        NaN

In [111]:
df['sales']=df['sales'].ffill()

In [112]:
df

        date  sales       city
0 2024-01-01  100.0  bangalore
1 2024-01-02  100.0       None
2 2024-01-03  100.0  bangalore
3 2024-01-04  160.0        NaN
4 2024-01-05  160.0     mumbai
5 2024-01-06  200.0        NaN

In [113]:
df['sales_bfill']=df['sales'].bfill()

In [114]:
df

        date  sales       city  sales_bfill
0 2024-01-01  100.0  bangalore        100.0
1 2024-01-02  100.0       None        100.0
2 2024-01-03  100.0  bangalore        100.0
3 2024-01-04  160.0        NaN        160.0
4 2024-01-05  160.0     mumbai        160.0
5 2024-01-06  200.0        NaN        200.0

In [115]:
df['sales'].ffill(limit=1)

0    100.0
1    100.0
2    100.0
3    160.0
4    160.0
5    200.0
Name: sales, dtype: float64

In [116]:
df

        date  sales       city  sales_bfill
0 2024-01-01  100.0  bangalore        100.0
1 2024-01-02  100.0       None        100.0
2 2024-01-03  100.0  bangalore        100.0
3 2024-01-04  160.0        NaN        160.0
4 2024-01-05  160.0     mumbai        160.0
5 2024-01-06  200.0        NaN        200.0

In [121]:
df['sales_interp']=df['sales'].interpolate()

In [122]:
df['sales']

0    100.0
1      NaN
2      NaN
3    160.0
4      NaN
5    200.0
Name: sales, dtype: float64

In [123]:

data={
    'ID':[1,None,3,4,5,6],
    'NAME':['ali','john','sara','None','john','david'],
    'AGE':[24,np.nan,22,20,np.nan,34],
    'SALARY':[50000,40000,None,70000,30000,20000],
    'DEPARTMENT':['HR','IT','FINANCE',None,'IT','IT']

}

df=pd.DataFrame(data)
df

    ID   NAME   AGE   SALARY DEPARTMENT
0  1.0    ali  24.0  50000.0         HR
1  NaN   john   NaN  40000.0         IT
2  3.0   sara  22.0      NaN    FINANCE
3  4.0   None  20.0  70000.0        NaN
4  5.0   john   NaN  30000.0         IT
5  6.0  david  34.0  20000.0         IT

In [135]:
df['ID']=df["ID"].interpolate()

In [136]:
df['ID']

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
5    6.0
Name: ID, dtype: float64

In [137]:
df

    ID   NAME   AGE   SALARY DEPARTMENT  ID_inter  ID_interp
0  1.0    ali  24.0  50000.0         HR       1.0        1.0
1  2.0   john   NaN  40000.0         IT       2.0        2.0
2  3.0   sara  22.0      NaN    FINANCE       3.0        3.0
3  4.0   None  20.0  70000.0        NaN       4.0        4.0
4  5.0   john   NaN  30000.0         IT       5.0        5.0
5  6.0  david  34.0  20000.0         IT       6.0        6.0